// Code generated by "stringer -type State -output state.strings.go"; DO NOT EDIT.

package pio

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Low-0]
	_ = x[High-1]
	_ = x[Unknown-255]
}

const (
	_State_name_0 = "LowHigh"
	_State_name_1 = "Unknown"
)

var (
	_State_index_0 = [...]uint8{0, 3, 7}
)

func (i State) String() string {
	switch {
	case i <= 1:
		return _State_name_0[_State_index_0[i]:_State_index_0[i+1]]
	case i == 255:
		return _State_name_1
	default:
		return "State(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
